name: deploy-to-pypi

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
          python-version: '3.7.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: continous integration
      run : |
        pip install -r requirements.txt
        python run_tests.py
    - name: prepare
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine setuptools
    - name: Package and Upload
      env:
        ADK_VERSION: ${{github.event.release.tag_name }}
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.TWINE_TOKEN }}
      run: |
        python3 setup.py sdist bdist_wheel --universal
        twine upload -r pypi dist/*
